### ISSUE TITLE
Where is the CloudFormation stack?

### ISSUE THREAD

**Issue by jamesladd** [serverless-components/fullstack-app#10]
Hi, 

When the stack is deployed and there is an error that requires the stack to manually removed, where can I find the cloudformation
stack in AWS Console to remove it? Is it not using CloudFormation?

**Comment by eahefnawy** [comment]
yeah components do no use CloudFormation, just raw API calls.

**Comment by austencollins** [comment]
There is no CloudFormation in Serverless Components (i.e. this entire project), so that error must be coming from somewhere else. 

If you would like to remove the entire project or part of it, please see this [section in the FAQ](https://github.com/serverless/components/blob/master/README.md#how-can-i-deploy-and-remove-multiple-components-at-the-same-time)
